### ISSUE TITLE
Move into testing-library org

### ISSUE THREAD

**Issue by jamesgorrie** [testing-library/playwright-testing-library#173]
More of a discussion than an issue - but are there any plans to integrate this repo back into the `testing-library` org?

**Comment by jrolfs** [comment]
@patrickhulce had mentioned it at one point, and I've been meaning to follow up on it. I'm definitely on board with doing so, but was hoping to work out #140 beforehand. Work has just gotten quite busy lately for me so I haven't had the time just yet.

**Comment by topaxi** [comment]
Are there any todos or obstacles doing this? I'd be happy to help out from a technical point of view :)

**Comment by patrickhulce** [comment]
I've pinged the core maintainers of the GitHub org for another update but they haven't gotten back to me yet. I doubt there are any serious technical obstacles (apart from republishing under new namespace in new deploy process) I think we're mostly waiting on process/access :)

**Comment by patrickhulce** [comment]
Got an update :) 

> once @jrolfs accepts the invite to the team, they should be able to do the following steps to bring Playwright TL into the group:
 Go to the Repositories tab and transfer the repository to the organization
 Set up any release automation and/or CI scripts there may be to be similar to the other repos in the org
 Add a section to @testing-library/testing-library-docs showing how to use the project

**Comment by jrolfs** [comment]
I just accepted the invite, thanks @patrickhulce! I’ll try to get things moved over in the next few days.

**Comment by jrolfs** [comment]
Seems I may need to first transfer this out of @hoverinc, so I'm working on that.

**Comment by MichaelDeBoey** [comment]
@kentcdodds can probably help @hoverinc transfer the repo

**Comment by patrickhulce** [comment]
@MichaelDeBoey the permissions to transfer *in* should already be there, IIRC GitHub has some restrictions on where you can transfer repos currently owned by organizations (e.g. I had to transfer to myself and then into another org in the past).

**Comment by jrolfs** [comment]
Yeah, our IT department is moving pretty slow here. I was considering detaching this fork anyways... is there any downside to just spinning up a new repository under @testing-library besides ⭐'s. What do we think about that?

**Comment by kentcdodds** [comment]
You can detach the fork without making a new repo. Check the settings.

**Comment by jrolfs** [comment]
Whoa, will do, thanks for the heads up @kentcdodds.

**Comment by jrolfs** [comment]
Heyyy, we're official now!! Thanks y'all for the help. I'll try to get a PR opened soon to add Playwright to the official Testing Library documentation :)

**Comment by kentcdodds** [comment]
Congrats! 👏👏

**Comment by jrolfs** [comment]
@kentcdodds I just realized I somehow managed to remove myself as an admin/owner of the repository through the multiple-step transfer process. Is there any chance you can fix that?

**Comment by kentcdodds** [comment]
I think I've fixed this 👍

**Comment by jrolfs** [comment]
Indeed, thank you :)
