### ISSUE TITLE
Basic example for Playwright Test fails with Error: toHaveValue can be only used with Locator object

### ISSUE THREAD

**Issue by petetnt** [testing-library/playwright-testing-library#356]
First of all, thanks for working with Testing Library Playwright support 🙏 

In the README there's this following test:

```ts
test('my form', async ({queries: {getByTestId}}) => {()
  const $email = await getByLabelText('Email')
  expect($email).toHaveValue('playwright@example.com')
})
```

However, this doesn't seem to work with `"@playwright/test": "1.17.1"`, and `"@playwright-testing-library/test": "4.0.1"`, but instead it fails with `Error: toHaveValue can be only used with Locator object`.

As mentioned in https://github.com/microsoft/playwright/issues/7835#issuecomment-887984627, these APIs are only ever meant to be used with `Locator` objects, not `ElementHandle`s.

This is possibly fixed / improved by https://github.com/testing-library/playwright-testing-library/pull/330 I guess? Not sure if there's any other workarounds.

**Comment by jrolfs** [comment]
Yeah, for this reason I’m hoping to implement some of the ideas in #330. I
didn’t realize the readme is incorrect, though. We’ll get that updated,
sorry!

**Comment by jrolfs** [comment]
I updated the readme, so I'm going to close this for now. I'm still planning on implementing a `Locator`-based API though!
