### ISSUE TITLE
getQueriesForElement is not returned by getByRole

### ISSUE THREAD

**Issue by davidchai717** [testing-library/playwright-testing-library#411]
Playwright version: 1.20.2
Playwright Testing Lib version: 4.2.1

I was trying to do something like this:
```js
const $secondaryNav = (
  await getByRole("navigation", {
    name: "Secondary Navigation Menu"
  })
).getQueriesForElement();
```

However it kept throwing a type error "getQueriesForElement is not a function".

Am I doing something wrong here? I can also confirm the getByRole query does return the proper element.

**Comment by jrolfs** [comment]
Hi @davidchai717, I'm so sorry it looks like the documentation was incorrect there. I'm assuming you are using the **@playwright/test** fixture? I went ahead and fixed the documentation in #412, but for your snippet there you'd want:

```ts
import { getQueriesForElement } from '@playwright-testing-library/test/fixture';

// ...

const $secondaryNav = getQueriesForElement(
  await getByRole("navigation", {
    name: "Secondary Navigation Menu"
  })
);
```

... or alternatively use `within`, as it's aliased to `getQueriesForElement` just like in [**@testing-library/dom**](https://testing-library.com/docs/dom-testing-library/api-within/):

```ts
import { within } from '@playwright-testing-library/test/fixture';

// ...

const $secondaryNav = within(
  await getByRole("navigation", {
    name: "Secondary Navigation Menu"
  })
);
```

Let me know if you still have any issues after trying the above suggestion and thank you for reporting this!
