### ISSUE TITLE
Using document from getDocument in a query causes a TypeError

### ISSUE THREAD

**Issue by flakey-bit** [testing-library/playwright-testing-library#478]
The[ snapshotter in Playwright attempts to call `setAttribute` on the element it is passed](https://github.com/microsoft/playwright/blob/20957f820d34a53003ab0722fa149c80fedec846/packages/playwright-core/src/server/trace/recorder/snapshotter.ts#L108).

This causes a TypeError (`setAttribute` is not a function) because no such function exists on `document`

![image](https://user-images.githubusercontent.com/4413825/186299880-00fe0601-a178-4ccc-b500-5a263e8abc39.png)

![image](https://user-images.githubusercontent.com/4413825/186300043-8de7ecac-df5e-49e4-974e-296a78766a05.png)

To reproduce:

```typescript
const $document = await getDocument(page);
await getByRole($document, "heading", { level: 2, name: "Prepare file for upload"});
```

Workaround:
```typescript
await page.mainFrame().evaluate(() => {
    Object.defineProperty(document, "setAttribute", { value: () => {}});
  });
```

**Comment by jrolfs** [comment]
I'm afraid I'm not super familiar with this Playwright feature, but I believe we're missing some additional context here? Can you have a look at my attempt to add a failing test [here̱](https://github.com/testing-library/playwright-testing-library/pull/479/commits/33eba079aa255b536ddd9cc9071967eb3a1e8839) and let me know if I'm missing something? It's currently passing.

**Comment by jrolfs** [comment]
@flakey-bit are you using **@playwright/test** to run your tests?

**Comment by flakey-bit** [comment]
Hi,

I can reproduce it in your repo (i.e. your "does not throw when recording trace + snapshots" test) [when I enable debugging](https://playwright.dev/docs/debug). See screenshots:

![image](https://user-images.githubusercontent.com/4413825/186526972-ec6a37ed-cf16-4932-b4be-b074c0d9489b.png)

![image](https://user-images.githubusercontent.com/4413825/186527332-807b55bf-a294-4fcc-9343-71d4e68cfe99.png)

![image](https://user-images.githubusercontent.com/4413825/186527409-d712d94d-7ad0-41e4-bb85-e24fdcd8978a.png)

![image](https://user-images.githubusercontent.com/4413825/186527453-62488ee4-4c14-4df8-be01-66d79e18ba66.png)

Note that your `beforeAll` opens up a page, but so does the test so you'll want to set the debugger on that window. Also note I've enabled the option to break on all exceptions.

**Comment by jrolfs** [comment]
Ok, so it doesn't actually cause the trace/test to fail it just breaks debugging?

**Comment by flakey-bit** [comment]
> Ok, so it doesn't actually cause the trace/test to fail it just breaks debugging?

"breaking debugging" is definitely a bit of a stretch. 

The reason I noticed this is that we're using React with an overlay that shows you any errors (when running in development mode) - see the second image in my first comment. Because of the error, the overlay was shown, obscuring the content in the videos Playwright recorded.

In production, the overlay is disabled.

I'm not 100% sure if the overlay is something we've added or whether it's part of React by default, however I know create-react-app has something similar.

**Comment by jrolfs** [comment]
> "breaking debugging" is definitely a bit of a stretch.

It _is_ an uncaught error in the page, so it definitely is a disruption (if we don't want to call it "breaking" 😉).

Unfortunately, I was unable to figure out how to assert that the error is not thrown as it doesn't seem to trigger `page.on('pageerror', () => {})`. I think I came up with a reasonable fix, though, so I'll get the released shortly.

Thanks for reporting this!

**Comment by flakey-bit** [comment]
Thanks so much for fixing this so quickly! And for the awesome library
