### ISSUE TITLE
how to read table header and do assertion?

### ISSUE THREAD

**Issue by InduKrish** [testing-library/playwright-testing-library#511]
const form = await this.screen.findByTestId( 'table-header-GroupCode');

Can you please advise if table headers can be verified with indexing?

**Comment by InduKrish** [comment]
_**<tr data-testid="table-header-GroupCode" class="css-62m37e" style="" css="1">
<th data-testid="cl-table-header-column--active" width="33.333333333333336%" class="css-a6vx1b">
<span class="css-1a91zmr" style="">
header 1
</span>
</th>
<th data-testid="cl-table-header-column--code" width="33.333333333333336%" class="css-a6vx1b">
<span class="css-1a91zmr" style="">
header 2
</span>
</th>
<th data-testid="cl-table-header-column--description" width="33.333333333333336%" class="css-a6vx1b">
<span class="css-1a91zmr" style="">
header 3
</span>
</th>
</tr>**_

**Comment by sebinsua** [comment]
What do you mean "verified with indexing"?

**Comment by InduKrish** [comment]
<img width="1654" alt="Screen Shot 2022-09-19 at 2 59 07 PM" src="https://user-images.githubusercontent.com/113629123/191105917-ec55b8de-f211-4a8f-8675-4647b20d1594.png">

I want to verify if 0th index matches to the header title in the table.. likewise index 1 matches the next header value. Attached is the DOM table strcuture.

In regular playwright , this how i verify the table header, Can you please advise how to do that using playwright testing library?

selector that gets passed to the following method is---->tableHeader : 'tr[data-testid=\'table-header-GroupCode\'] th span',
 async verifyElementContainsText(selector, index, text) {
    await this.page.waitForSelector(selector);
    return await expect(this.page.locator(selector).nth(index)).toContainText(text);
  }

**Comment by jrolfs** [comment]
This might be a bug as the `*AllBy` queues should return a `Locator` for all the matched elements. I'll take a look when I have a chance.

**Comment by jrolfs** [comment]
Nevermind, this isn't a bug... I have a test case for this already.

https://github.com/testing-library/playwright-testing-library/blob/1b41bd5e5de2c22d618b07ff5982997da043bd7c/test/fixture/locators.test.ts#L217-L223

In your example `await this.screen.findAllByTestId('table-header-GroupCode')` is selecting the parent element (`tr`) and therefore its `textContent()` includes all of the child `th` element's content.

You'd want this for your example markup (select the `th` elements by test ID using a `RegExp`):

https://github.com/testing-library/playwright-testing-library/blob/5b09ee482b98b07afe94e8ee9a0a9546844c7890/test/fixture/locators.test.ts#L226
