### ISSUE TITLE
findByText still fails after adding await.

### ISSUE THREAD

**Issue by InduKrish** [testing-library/playwright-testing-library#519]
This is related to ticket #513

with by getByText, the test passed, and attached is the screenshot.

       const header = await this.screen.findByTestId('erow-GroupCode-0');
        console.log(" header" + header)
        const base = this.within(header).getByText("LINEHOLDER")
        console.log("base value" + base);
        const check = this.within(header).getByText("check")
        console.log(" value " + check)
        await expect(base).toContainText(text);

<img width="1792" alt="Screen Shot 2022-09-20 at 10 15 18 AM" src="https://user-images.githubusercontent.com/113629123/191298060-06501511-780c-4d2b-b35a-016abdf9e23c.png">

when I tried to test this findByText with await as suggested by #513, and i see the following error
        const header = await this.screen.findByTestId('erow-GroupCode-0');
        console.log(" header" + header)

        const base = await this.within(header).findByText("LINEHOLDER")
        console.log("base value" + base);

        const check = await this.within(header).findByText("check")
        console.log(" value " + check)

        await expect(base).toContainText(text);

<img width="1792" alt="Screen Shot 2022-09-20 at 10 14 50 AM" src="https://user-images.githubusercontent.com/113629123/191298088-fdcadfe9-42b3-449a-b659-777faa0aafed.png">

html structure:

<img width="1180" alt="Screen Shot 2022-09-20 at 10 23 35 AM" src="https://user-images.githubusercontent.com/113629123/191299039-f3f93d5c-3c30-46a8-8a34-8c2e3edf2537.png">

**Comment by jrolfs** [comment]
This is the same issue as #521, see my comment there https://github.com/testing-library/playwright-testing-library/issues/521#issuecomment-1253014806:

> It looks like you're attempting to click on the SVG <title /> element, which is not a visible element.

**Comment by jrolfs** [comment]
This does bring up an issue of consistency between `queryBy` + `getBy` and `findBy` in that the `findBy` queries use Playwright's `waitFor` and default to `{ state: 'visible' }`, but `getBy` and `queryBy` don't check the state of the element with Playwright which is effectively `{ state: 'attached' }` I think.

This is related to #506, but I will create a separate issue specifically for the consistency issue I described above.
