### ISSUE TITLE
Question:  Unable to click the link

### ISSUE THREAD

**Issue by InduKrish** [testing-library/playwright-testing-library#565]
Can you please advise how to click the link in the web table, tried the following code. and it return an error.. Attached is the table screenshot and error log. Both the way are returning the same error.

 proxy.click: Target closed
    =========================== logs ===========================
    waiting for selector "query-by-text=[2023]"
      selector resolved to visible <a href="/resource?href=https://service.cbna.dev0.d…>2023</a>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      <div class="css-11d9xqn" data-testid="sub-header-IFVa…>Vacation Bid & Award</div> from <div class="app__sidebar">…</div> subtree intercepts pointer events
    retrying click action, attempt #1

Screenshot is atatched.

1.
```javascript
  const cell = await screen.queryByTestId("paged-table-IFVacationAuctionSummaries").within().getAllByRole('link');
  const noOfCells = await screen.queryByTestId("paged-table-IFVacationAuctionSummaries").within().queryAllByRole('link').count();
        console.log("year value" + await cell.nth(0).textContent() )
  

        for (let j = 0; j < noOfCells; j++) {
            console.log(" value1 " + await cell.nth(j).textContent())
        if ((await cell.nth(j).textContent()) === '2023') {. 
            console.log(" value 2" + await cell.nth(j).textContent())
            await cell.nth(j).click();   
        }
    }
```

2.
```javascript
 await screen.queryByText(new Date().getFullYear() + 1).click();  ---> it worked once and but not consistent, screenshot is attached. trying to click 2023 in the table displayed in the screenshot.
```

<img width="1422" alt="Screen Shot 2022-10-19 at 10 26 41 PM" src="https://user-images.githubusercontent.com/113629123/196850666-74ededaa-9930-418d-a73f-ac0781f9c2c8.png">

<img width="1474" alt="Screen Shot 2022-10-19 at 10 49 47 PM" src="https://user-images.githubusercontent.com/113629123/196852197-b24f29d2-17bb-4e45-b6fa-b38ee5aed8e5.png">

<img width="1474" alt="Screen Shot 2022-10-19 at 11 04 54 PM" src="https://user-images.githubusercontent.com/113629123/196853909-31f16751-d899-4070-b636-428244eddc6b.png">

Can you please advise why? and please suggest me if there is a better solution , Thank you!

**Comment by jrolfs** [comment]
It looks like an element is obstructing the element you're attempting to interact with (`<div class="app__sidebar">`). It's possible that the sidebar element is invisible but still overlapping with the element you're attempting to `.click()`. This is more of a test flakiness/debugging issue or potentially an issue with Playwright, not Playwright Testing Library.

**Comment by jrolfs** [comment]
I'm going to close this for now, but let me know if you want to continue this over in Discussions-land.
