### ISSUE TITLE
how to access a partially visible text with its -actual value

### ISSUE THREAD

**Issue by msabya** [testing-library/playwright-testing-library#573]
I have a list box which contains year from - 2023 til 2028.
But in the UI the list box is shown in a compact form so only first 3 digits of the above values are shown. e.g. 202 instead of 2023 and 202 instead of 2028.

in my automation scenario how will i handle such a case where i want to select 3rd or 4th value in the list and access it by its value 2025 or 2026 while the UI still shows 202 for all the values. Refer the attached screen shot below

**Comment by msabya** [comment]
await actor.attemptsTo

**Comment by msabya** [comment]
Appreciate if feed back if any on this from the @playwright team

**Comment by jrolfs** [comment]
@msabya just so you know, this isn't the official Playwright project. Regardless, this issue needs more information. What have you tried to do to select the element? Are you using **playwright-testing-library** to do so?

**Comment by jrolfs** [comment]
See: https://github.com/testing-library/playwright-testing-library/issues/597#issuecomment-1441248688
